### PR TITLE
change custom_types contract to be equivalent to the one in soroban-cli

### PR DESCRIPTION
**Pull request by BlaineHeffron**
### What

Changing custom_types contract to match the one in stellar-cli.

### Why

This allows us to use `soroban client init` in the `js-stellar-sdk` instead of using prebuilt wasms. We needed functions to do tests on. I noticed that custom_types in this repo was identical to increment so I figured it was fine to change it.

### Known limitations

N/A

### CODE REVIEW

**Review by chadoh — APPROVED** [review]
Thanks! I want to add that this will also allow us to use `soroban contract init` to set up tests in stellar-cli, rather than include its own modified versions of `soroban-examples` in the `test-wasms` folder.

**Comment by chadoh** [comment]
Note  that a CI test for the custom_types contract is [now failing](https://github.com/stellar/soroban-examples/actions/runs/9603054896/job/26485364057?pr=313)

**Review by willemneal — APPROVED** [review]

**Comment by BlaineHeffron** [comment]
formatting should be fixed now

**Review by willemneal — APPROVED** [review]

**Comment by willemneal** [comment]
@BlaineHeffron @ElliotFriend , one Test is failing and I can't seem to have the permissions to re-run it.

**Review by willemneal — APPROVED** [review]

**Review by fnando — APPROVED** [review]

**Pull request merged**
